In [39]:
import tensorflow as tf
import pandas as pd
import numpy as np
import pickle
from tensorflow.keras.models import load_model

In [40]:
##Load the trained model,scaler and encoder pickel
model=load_model('model.h5')

with open('labelencoder.pkl','rb') as file:
    label_encoder=pickle.load(file)

with open('onehot_encoder.pkl','rb') as file:
    onehot_encoder=pickle.load(file)

with open('Scaler.pkl','rb') as file:
    scaler=pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [41]:
input_data={
    'CreditScore':600,
    'Geography':'France',
    'Gender':'Male',
    'Age':40,
    'Tenure':3,
    'Balance':60000,
    'NumOfProducts':2,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':50000
}

In [42]:
geo_encoded=onehot_encoder.transform([[input_data['Geography']]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=onehot_encoder.get_feature_names_out(['Geography']))

c:\Users\KIIT0001\OneDrive\Desktop\churn_modelling\.venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [43]:
geo_encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [44]:
input_data

{'CreditScore': 600,
 'Geography': 'France',
 'Gender': 'Male',
 'Age': 40,
 'Tenure': 3,
 'Balance': 60000,
 'NumOfProducts': 2,
 'HasCrCard': 1,
 'IsActiveMember': 1,
 'EstimatedSalary': 50000}

In [45]:
input_df=pd.DataFrame([input_data])

In [46]:
input_df

   CreditScore Geography Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France   Male  ...          1               1            50000

[1 rows x 10 columns]

In [47]:
input_df.drop(columns=['Geography'],inplace=True)

In [ ]:
input_data=pd.concat([input_df,geo_encoded_df],axis=1)

In [49]:
input_df

   CreditScore Gender  ...  Geography_Germany  Geography_Spain
0          600   Male  ...                0.0              0.0

[1 rows x 12 columns]

In [50]:
input_df['Gender']=label_encoder.transform(input_df['Gender'])

In [51]:
input_df

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          600       1  ...                0.0              0.0

[1 rows x 12 columns]

In [52]:
input_df_scaled=scaler.transform(input_df)

In [53]:
input_df_scaled

array([[-0.52167756,  0.90590537,  0.09702702, -0.70361616, -0.25696274,
         0.79664949,  0.64589732,  0.9757929 , -0.86859095,  0.99352099,
        -0.57735027, -0.57234647]])

In [55]:
prediction=model.predict(input_df_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step

In [56]:
prediction

array([[0.0386315]], dtype=float32)

In [57]:
prediction_prob=prediction[0][0]

In [58]:
if prediction_prob >0.5:
    print("the customer is likely to churn.")
else:
    print("the customer is not likely to churn.")

the customer is not likely to churn.